apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
spec:
  replicas: 1
  serviceName: db-service
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db-pod
          image: postgres:12.12
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: root
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-data
              mountPath: /usr/data
  selector:
    matchLabels:
      app: db
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
